apiVersion: v1
kind: Service
metadata:
  name: udacity-devops-capstone-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
      name: udacity-devops-capstone
      protocol: TCP
  selector:
    app: udacity-devops-capstone