version: 2.1
orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3

jobs:
  build-docker:
    docker:
      - image: circleci/python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            sudo chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint

  push-docker-images:
    docker:
      - image: "cimg/python:3.10"
        user: root
    steps:
      - checkout
      - setup_remote_docker:
          version: "20.10.14"
          docker_layer_caching: false
      - run:
          name: push to docker hub
          command: |
            docker logout docker.io
            docker login docker.io -u $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
            docker build . -t natsudragneel98/udacity-devops-capstone:latest
            docker tag natsudragneel98/udacity-devops-capstone:latest natsudragneel98/udacity-devops-capstone:latest
            docker push docker.io/natsudragneel98/udacity-devops-capstone:latest

  create-aws-kubectl-cluster:
    docker:
      - image: "cimg/python:3.10"
    steps:
      - checkout
      - aws-eks/create-cluster:
          cluster-name: udacity-devops-capstone-cluster
          aws-region: us-west-2
          node-type: t3.medium
          nodes-min: 1
          nodes-max: 3                    

  project-deployment:
    docker:
      - image: "cimg/python:3.10"
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: udacity-devops-capstone-cluster
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          resource-file-path: deployment.yaml
          show-kubectl-command: true
      - kubernetes/create-or-update-resource:
          resource-file-path: service.yaml
          show-kubectl-command: true    
      - kubernetes/create-or-update-resource:
          resource-file-path: eks.yaml
          show-kubectl-command: true
      - run:
          command: |
            kubectl get nodes -o wide
            kubectl get all 
            kubectl get svc -o wide
            kubectl describe pods

workflows:
  deployment:
    jobs:
      - build-docker
      - push-docker-images:
          requires:
            - "build-docker"
      - create-aws-kubectl-cluster:
          requires:
            - "build-docker"
      - project-deployment:
          requires: [push-docker-images, create-aws-kubectl-cluster]